name: Commit date to master
on: push
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v2-beta # use either @v2-beta or @master. Eventually there will be a @v2 tag.

      - name: get recent files
        run: |
          # do some operation that changes a file in the git repo
          git log --pretty=format: --name-only --since="7 days ago"  > recent.md
  
      - uses: stefanzweifel/git-auto-commit-action@v4
